defaults:
  - _self_
  - model@model: pytorch_build_model
  - trainer: default
  - params: default
  - callbacks: default
  - data: default  # Добавляем ссылку на даталоадеры
  

params:
  checkpoint_path: logs/Linknet/checkpoints
trainer:  
  default_root_dir: logs/Linknet
  logger:
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: logs/Linknet
    name: resnet101 #resnet34
    flush_logs_every_n_steps: 5  