defaults:
  - _self_
  - model@model: pytorch_build_model
  - trainer: default
  - params: default
  - callbacks: default
  

params:
  checkpoint_path: logs/DeepLabV3/checkpoints
trainer: 
  default_root_dir: logs/DeepLabV3
  logger:
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: logs/DeepLabV3
    name: resnet34
    flush_logs_every_n_steps: 5  