model:
  name: "mask_rcnn"  # Выбор модели: mask_rcnn, ssd300
  num_classes: 2
  lr: 0.0001

infer:
  input_dir: "detection/test_images"  # Папка с изображениями для предсказания
  score_threshold: 0.5  # Порог уверенности
