train_ratio: 0.9
num_workers: 8 
batch_size:  16
seed: 1
accelerator: cuda
max_epochs: 200
checkpoint_path: logs/UNet_simple/checkpoints
image_path: ../seg_dataset/images
mask_path: ../seg_dataset/maps_roads
log_every_n_steps: 100
devices:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7