#train_ratio: 0.9
num_workers: 8
batch_size:  16
seed: 1
accelerator: gpu
max_epochs: 80
checkpoint_path: logs/Linknet/checkpoints #logs/UNet_simple/checkpoints
#image_path: ../seg_dataset/images_new
#mask_path: ../seg_dataset/maps_roads_new
log_every_n_steps: 200
architecture: Linknet
img_size: 224
devices:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7 